name: Tests

on:
  push:
    branches:
      - main

jobs:

  Tests:

    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: "Install Node.js"
        uses: actions/setup-node@v3

      - name: "Install Mocha"
        run: npm install -g mocha

      - name: "Install dependencies"
        run: npm install

      - name: "Run tests"
        run: |
            mkdir coverage
            npm test
            npm run coverage

      - name: "Generate a coverage report"
        if: always()
        run: npm run coverage

      - name: "Post coverage data to Coveralls"
        if: always()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
