name: Test

on:
  push:
    branches:
      - main

jobs:

  test-test:

    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: "Install Node.js"
        uses: actions/setup-node@v3

      - name: "Install Mocha"
        run: npm install -g mocha

      - name: "Install dependencies"
        run: npm install

      - name: "Generate coverage data"
        run: |
             mkdir coverage &&
             node_modules/.bin/jscover library/src src-cov &&
             mv -f library/src library/src-orig &&
             mv -f src-cov library/src

      - name: "Run tests"
        run: npm test

      - name: "Post coverage data to Coveralls"
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
