name: Test

on:
  push:
    branches:
      - main

jobs:

  test-test:

    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: "Install Node.js"
        uses: actions/setup-node@v3

      - name: "Install Mocha"
        run: npm install -g mocha

      - name: "Install dependencies"
        run: npm install

      - name: "Generate coverage data"
        run:  rm -rf coverage
              rm -rf lib-cov

              mkdir coverage

              node_modules/.bin/jscover library/src library/src-cov
              mv library/src library/src-orig
              mv library/src-cov library/src
              node_modules/.bin/mocha -R mocha-lcov-reporter > coverage/coverage.lcov
              rm -rf library/src
              mv library/src-orig library/src

      - name: "Run tests"
        run: npm test

      - name: "Post coverage data to Coveralls"
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
